### ISSUE TITLE
Add architecture diagram to user-guide

### ISSUE THREAD

**Issue by ansijain** [kubevirt/user-guide#423] opened 2021-04-06 11:03 UTC
Addition of https://github.com/kubevirt/kubevirt/blob/master/docs/architecture.md to user-guide[https://github.com/kubevirt/user-guide/blob/master/docs/architecture.md] for better understanding of kubevirt components

**Comment by mazzystr** [comment] 2021-04-08 02:11
@ansijain Would you mind if I closed this issue as duplicate of [issues/348](https://github.com/kubevirt/user-guide/issues/348)?

**Comment by ansijain** [comment] 2021-04-08 02:19
Yes.
Sorry I didn't noticed it exists

**Comment by mazzystr** [comment] 2021-04-09 16:55
Cool, Thanks!  Duplicate label added.  Closing...

**Closed by mazzystr** 2021-04-09 16:55 UTC
Labels: triage/duplicate
